# Generated by Django 4.0.3 on 2022-03-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_products_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Vendors',
        ),
    ]
