# Generated by Django 4.0.3 on 2022-03-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contacts',
        ),
    ]
