# Generated by Django 4.0.3 on 2022-03-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
