# Generated by Django 4.0.3 on 2022-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_products_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.CharField(default='x', max_length=1000),
            preserve_default=False,
        ),
    ]
